COMMON: &COMMON
  author: "Hiro"

  logo:
    source: "http://www.msn.to/image/wings.jpg"
    wudth: 215
    height: 67

  development:
    hoge: "dev"
    <<: *COMMON

  test:
    hoge: "test"
    <<: *COMMON

  production::
    hoge: "pro"
    <<: *COMMON
